lesson02 version01
barsetca/GeekBrains_Java2 pull request #2
Opened 2020-02-25 06:02 UTC by barsetca

Для сокращения дублирования кода при тестировании различных вариантов заполнения массива обработку наших исключений вывел в отдельный метод в тестовом классе (там же где main). Main для генерации вариантов массива, вызова тестового метода и вывода на консоль. Это несколько нарушает требование ДЗ делать всё в main. Надеюсь это не будет проблемой))

2020-02-25 21:33 UTC, OKrylov requested changes
В целом все отлично, есть только одно небольшое замечание

2020-02-25 21:33 UTC, OKrylov commented on src/lesson02/util/SumUtil.java
> +        if (integers == null || integers.length != ARRAY_ROWS || integers[0].length != ARRAY_COLUMN) {
что если 2, 3 или 4 строка массива имеет длину != 4?

2020-02-26 06:14 UTC, barsetca commented on src/lesson02/util/SumUtil.java
> +        if (integers == null || integers.length != ARRAY_ROWS || integers[0].length != ARRAY_COLUMN) {
Привет!
Да, решение для "прямоугольного" 2д массива. Добавил цикл проверки по длине каждой строки массива
https://github.com/barsetca/GeekBrains_Java2/pull/2/commits/c2595ddc6ff621afa52c406245f9f95426d29ce0

2020-02-26 06:17 UTC, barsetca commented
Привет!
Да, решение для "прямоугольного" 2д массива. Добавил цикл проверки по длине
каждой строки массива
https://github.com/barsetca/GeekBrains_Java2/pull/2/commits/c2595ddc6ff621afa52c406245f9f95426d29ce0

ср, 26 февр. 2020 г. в 00:33, OKrylov <notifications@github.com>:

> *@OKrylov* requested changes on this pull request.
>
> В целом все отлично, есть только одно небольшое замечание
> ------------------------------
>
> In src/lesson02/util/SumUtil.java
> <https://github.com/barsetca/GeekBrains_Java2/pull/2#discussion_r384138789>
> :
>
> > @@ -0,0 +1,29 @@
>
> +package lesson02.util;
>
> +
>
> +import lesson02.exceptions.MyArrayDataException;
>
> +import lesson02.exceptions.MyArraySizeException;
>
> +
>
> +public class SumUtil {
>
> +
>
> +    public static final int ARRAY_ROWS = 4;
>
> +    public static final int ARRAY_COLUMN = 4;
>
> +
>
> +    public static int summarizeArraysElements(String[][] integers) throws MyArraySizeException, MyArrayDataException {
>
> +        if (integers == null || integers.length != ARRAY_ROWS || integers[0].length != ARRAY_COLUMN) {
>
>
> что если 2, 3 или 4 строка массива имеет длину != 4?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/barsetca/GeekBrains_Java2/pull/2?email_source=notifications&email_token=ANOVSE7YNXGWTIZ54AZZQILREWFEBA5CNFSM4K252V22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCW4UN6Y#pullrequestreview-364463867>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANOVSE6I24RUUTUTJSULXMTREWFEBANCNFSM4K252V2Q>
> .
>

2020-02-26 06:50 UTC, merged

2020-03-25 22:40 UTC, OKrylov reviewed
По ДЗ все отлично, замечаний не имею